routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* HOME PAGE */
Route::get('/', 'Admin\HomeController@homePageRedirect');

/* AUTH */
Auth::routes(['register' => false, 'verify' => true]);
Route::get('/logout', 'Auth\LoginController@logout');
Route::get('/email/verify-finished', 'Auth\VerificationController@verifyFinished');

/* CORE ROUTES */
Route::any('/p/{all}', 'Admin\PagesController@init')->where('all', '.*');
Route::any('/component/{all}', 'Admin\ComponentsController@init')->where('all', '.*');
Route::any('/func/{all}', 'Admin\FuncsController@init')->where('all', '.*');

/* CORE HELPER ROUTES */
Route::any('/helper/custom-input-form', 'Admin\HelpersController@customInputForm')->where('all', '.*');
Route::any('/helper/get-entity-items-json', 'Admin\HelpersController@getEntityItemsJson')->where('all', '.*');
Route::any('/helper/get-table-component-csv', 'Admin\HelpersController@getTableComponentCsv')->where('all', '.*');

/* FILES */
Route::any('files/dz-upload', 'Admin\FilesController@dzUpload');
Route::resource('files', 'Admin\FilesController')->except(['index', 'create', 'show', 'edit', 'update']);

/* CUSTOM ROUTES */
Route::get('cr/invoice-pdf', 'Admin\CustomRoutesController@downloadInvoice');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/* HOME PAGE */
Route::any('/', 'Web\IndexController@index');

/* IMAGE RESIZER */
Route::get('media/image/{image}/{width?}/{height?}', 'MediaController@displayImage');

/* CUSTOM ROUTES */

app/Func.php
<?php

namespace App;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;

class Func
{
    /**
     * Converts response data to JSON.
     * Do not remove this function
     *
     */
    public static function response($data, $noSwal = false){
        if(!isset($data["state"])) $data["state"] = "error";
        if(!isset($data["msg"])){
            if($data["state"] == "success")
                $data["msg"] = __("Done!");
            elseif($data["state"] == "error")
                $data["msg"] = ["title" => __("Error!"), "html" => __("Oops, unexpected error, please try again later.")];
            else
                $data["msg"] = "";
        }

        if(!isset($data["attach_script"])) $data["attach_script"] = "";

        /*if(!isset($data["actions"])) $data["actions"] = [];
        if(!empty($data["actions"])){
            foreach ($data["actions"] as &$action) {
                $action = DefProcessor::getByRef($action);
            }
        }*/

        /* SWAL DATA */
        if(!$noSwal)
            $data["swal_data"] = Helper::getSwalDataFromFlash($data["state"], $data["msg"]);

        return json_encode($data);
    }

    public static function functionExists($function){
        $function = self::getFunctionClassName($function);
        return class_exists($function);
    }

    public static function getFunctionClassName($function, $incNamespace = true){
        return ($incNamespace ? "\App\Functions\\" : "").ucfirst(Str::camel($function))."Function";
    }

    public function getName(){
        return strtolower(Str::snake(str_replace(["App\Functions\\", "Function"], "", get_called_class())));
    }
}

resources/views/admin/inc/component_redirect_back.blade.php
<script type="text/javascript">window.Front.goBackOrHome();</script>
<div class="component-placeholder d-flex justify-content-center align-items-center">
    <div class="component-redirecting">
        <h2><i class="spinner spinner-border text-primary"></i> {{ __('Redirecting') }}...</h2>
        <p>{{ __("Please wait for redirection to finish. If nothing is happening, simple press browser's back back button or go to the different page.") }}</p>
    </div>
</div>

resources/views/admin/inc/flash_msg.blade.php
<?php
    $states = \App\Helper::getFlashStates();
    /* get keep now */
    $keepNow = (Session::has('keep-now') && Session::get('keep-now'));

    /* forget keep now */
    if(Session::has('keep-now')) Session::forget('keep-now');
?>
@foreach (['error', 'warning', 'success', 'info'] as $flashState)
    @if(Session::has($flashState))
        <?php
            $flash = Session::get($flashState);

            /* forget current message when displayed once */
            if(!$keepNow)
                Session::forget($flashState);

            if(is_array($flash) && isset($flash["inLineReport"]) && $flash["inLineReport"] && isset($flash["html"])){
                if(!is_array($flash["html"])){
                    $flash["html"] = array($flash["html"]);
                }
                foreach ($flash["html"] as $flashMsg){
                    if(!is_array($flashMsg)){
                        $flashMsg = [
                            "state" => $flashState,
                            "msg" => $flashMsg
                        ];
                    }
                    ?>
                        <div class="alert alert-{{ $states[$flashMsg["state"]]["color"] }} alert-dismissible fade show">
                            <button type="button" class="close" data-dismiss="alert">&times;</button>
                            <i class="{{ $states[$flashMsg["state"]]["icon"] }}"></i> {{ $flashMsg["msg"] }}
                        </div>
                    <?php
                }
            }
            else{
                $swalData = \App\Helper::getSwalDataFromFlash($flashState, $flash);
        ?>
                <script type="text/javascript">
                    Swal.fire({!! json_encode($swalData) !!});
                </script>
        <?php } ?>
    @endif
@endforeach

resources/views/admin/inc/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm fixed-top" id="top-navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('admin/') }}">
            @if(!empty($appDef["data"]["logo"]))
                <img src="{{ asset($appDef["data"]["logo"]) }}" alt="{{ config('app.name', 'AnyAdmin') }}" />
            @else
                {{ config('app.name', 'AnyAdmin') }}
            @endif
        </a>

    @if(Auth::check())
        <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <button type="button" id="sidebarCollapse" class="btn btn-outline-">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </ul>
    @endif

    <!-- Right Side Of Navbar -->
        <ul class="navbar-nav ml-auto">
            <!-- Authentication Links -->
            @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}"><i class="fa fa-unlock-alt"></i> {{ __('auth.login.title') }}</a>
                </li>
                @if (Route::has('register'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @endif
            @else
                <li class="nav-item dropdown">
                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                        <i class="far fa-user"></i> <span class="d-none d-md-inline">{{ Auth::user()->name }}</span> <span class="caret"></span>
                    </a>

                    <div class="dropdown-menu dropdown-menu-right user-dropdown-menu pt-0" aria-labelledby="navbarDropdown">
                        <div class="text-center bg-secondary text-light border-bottom pb-2 pt-2"><i class="fa fa-user"></i> <b>{{ Auth::user()->name }}</b></div>
                        <a class="dropdown-item pt-2" href="javascript:void(0);" onclick="@include("admin.inc.elements._action", ['action' => $definitions->get("app")["data"]["custom_actions"]["edit_user_account"]["action"], 'actionAdditionalData' => ["entity" => "user", "id" => Auth()->user()->id]])">
                            <i class="fa fa-user-cog"></i> {{ __('Account settings') }}
                        </a>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                            <i class="fa fa-power-off"></i> {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            @endguest
        </ul>
    </div>
</nav>
<div class="navbar-placeholder"></div>

resources/views/admin/inc/sidebar.blade.php
<nav id="sidebar">
    <ul id="sidebar-menu" class="list-unstyled components fixed-top">
        @foreach($appDef["data"]["menu"] as $itemKey => $item)
            <?php
            $hasRights = false;
            $active = false;
            if(!empty($item["target"]) && !is_array($item["target"])){
                $hasRights = $definitions->userHasRights(Auth::user(), "pages.".$item["target"]);
                $active = (isset($page) && $page["name"] == $item["target"]);
            }
            elseif(is_array($item["target"])){
                if(isset($item["access"])){
                    $hasRightsLink = Auth::user()->hasRights($item); //check if has rights for the link
                    if(!$hasRightsLink){
                        continue;
                    }
                }

                foreach ($item["target"] as $item2){
                    if(!empty($item2["target"]) && !is_array($item2["target"])){
                        if(!$hasRights)
                            $hasRights = $definitions->userHasRights(Auth::user(), "pages.".$item2["target"]);

                        if(!$active)
                            $active = (isset($page) && $page["name"] == $item2["target"]);
                    }
                }
            }
            ?>
            @if($hasRights)
                <li{!! $active ? ' class="active"' : '' !!}>
                    @if(is_array($item["target"]))
                        <a href="#submenu-{{ $itemKey }}" data-toggle="collapse" aria-expanded="{{ $active ? 'true' : 'false' }}" class="dropdown-toggle"{!! !empty($item["tooltip"]) ? ' data-tooltip data-placement="bottom" title="'.$item["tooltip"].'"' : '' !!}>@if(!empty($item["icon"]))<i class="menu-icon {{ $item["icon"] }}"></i> @endif {{ __($item["title"]) }}</a>
                        <ul class="collapse list-unstyled{{ $active ? ' show' : '' }}" id="submenu-{{ $itemKey }}">
                            @foreach($item["target"] as $item2)
                                <?php
                                if(empty($item2["target"]) || is_array($item2["target"])){
                                    $item2["target"] = "";
                                }
                                else{
                                    $targetDef = $definitions->get('pages.'.$item2["target"]);
                                    $hasRights = $definitions->userHasRights(Auth::user(), "pages.".$item2["target"]);

                                    if(empty($item2["title"])){
                                        $item2["title"] = !empty($targetDef["data"]["title"]) ? $targetDef["data"]["title"] : "";
                                    }
                                    if(empty($item2["icon"])){
                                        $item2["icon"] = !empty($targetDef["data"]["icon"]) ? $targetDef["data"]["icon"] : "";
                                    }
                                }
                                ?>
                                @if($hasRights)
                                    <li><a{!! !empty($item2["tooltip"]) ? ' data-tooltip data-placement="bottom" title="'.$item2["tooltip"].'"' : '' !!} href="{{ !empty($item2["target"]) ? url('admin/p/'.$item2["target"]) : "#x" }}">@if(!empty($item2["icon"]))<i class="menu-icon {{ $item2["icon"] }}"></i> @endif {{ __($item2["title"]) }}</a></li>
                                @endif
                            @endforeach
                        </ul>
                    @else
                        <?php
                        if(!empty($item["target"])){
                            $targetDef = $definitions->get('pages.'.$item["target"]);

                            if(empty($item["title"])){
                                $item["title"] = !empty($targetDef["data"]["title"]) ? $targetDef["data"]["title"] : "";
                            }
                            if(empty($item["icon"])){
                                $item["icon"] = !empty($targetDef["data"]["icon"]) ? $targetDef["data"]["icon"] : "";
                            }
                        }
                        ?>
                        <a href="{{ !empty($item["target"]) ? url('admin/p/'.$item["target"]) : "#x" }}">@if(!empty($item["icon"]))<i class="menu-icon {{ $item["icon"] }}"></i> @endif {{ __($item["title"]) }}</a>
                    @endif
                </li>
            @endif
        @endforeach
        <li class="menu-logout-link">
            <a href="{{ url('admin/logout') }}"><i class="menu-icon fa fa-power-off"></i> {{ __('Logout') }}</a>
        </li>
    </ul>
</nav>